import { MainNav } from "@/components/main-nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserNav } from "@/components/user-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kwikdeploy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-screen-xl min-h-screen mx-auto border-2 shadow-sm rounded-md p-4">
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <MainNav className="" />
              <div className="ml-auto flex items-center space-x-4">
                <UserNav />
              </div>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
