
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MainNav } from "./components/main-nav";
import ManiNavContainer from "@/components/ui/main-nav-container";
import ClientOnly from "./components/client-only";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kwikdeploy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <ManiNavContainer />
          {children}
        </ClientOnly>
      </body>
    </html>
  );
}
